require "json"

class Godaddy::VerificationRealName
  STATUSES = %w(APPROVED PENDING REJECTED_DOCUMENT_OUTDATED
    REJECTED_EXPIRED_BUSINESS_LICENSE REJECTED_EXPIRED_ORGANIZATION_CODE
    REJECTED_ILLEGIBLE_DOCUMENT_NAME REJECTED_ILLEGIBLE_IDENTIFICATION
    REJECTED_INCOMPLETE_IDENTIFICATION REJECTED_INCOMPLETE_REGISTRATION_LETTER
    REJECTED_INCONSISTENT_IDENTITY_CARD REJECTED_INCONSISTENT_ORGANIZATION_CODE
    REJECTED_INCONSISTENT_REGISTRANT_NAME
    REJECTED_INVALID_BUSINESS_LICENSE_OR_ORGANIZATION_CODE
    REJECTED_INVALID_DOCUMENT REJECTED_MISMATCH_BUSINESS_ID
    REJECTED_MISMATCH_BUSINESS_NAME REJECTED_MISMATCH_DOCUMENT_ID
    REJECTED_MISMATCH_DOCUMENT_NAME REJECTED_MISMATCH_DOCUMENT_TYPE
    REJECTED_MISMATCH_REGISTRANT_INFO REJECTED_MISMATCH_REGISTRANT_LOCALITY
    REJECTED_MISMATCH_REGISTRANT_NAME REJECTED_UNABLE_TO_OPEN
    REJECTED_UNABLE_TO_VERIFY REJECTED_UNKNOWN_ERROR UNABLE_TO_RETRIEVE_STATUS)

  JSON.mapping(
    status: String
  )
end
